---
#- name: Install the devpi server
#  hosts: mravi1
#  remote_user: root
#  sudo_user: root
#  sudo: yes
#  roles:
#    - devpi

- name: Install bandersnatch server
  hosts: localhost 
  remote_user: root
  sudo: yes
  roles:
    - bandersnatch
  tags:
    - bandersnatch
