---

- name: create bandersnatch user
  user:
     name: "{{ bandersnatch_username }}"
     home: "{{ bandersnatch_home_dir }}"
     move_home: yes

- name: Install virtualenv and apache server pkgs
  apt: name={{ item }}
  with_items:
     - python-virtualenv
     - apache2

- name: Creating folders to store relevant logs
  file: path=/var/log/bandersnatch state=directory

- name: Installing the stable version of bandersnatch
  pip: name=bandersnatch virtualenv={{ bandersnatch_virtual_env }}

- name: placing the bandersnatch config file in /etc
  template: 
     src: bandersnatch.conf 
     dest: /etc/bandersnatch.conf

- name: Creating a directory to store the bandersnatch mirrors
  file: path=/srv/pypi state=directory

- name: copy the apache2.conf file to /etc/apache2 location
  copy: src=apache2.conf dest=/etc/apache2/apache2.conf

- name: Moving the pypi.conf file to sites-available under apache server
  template: 
      src: etc/apache2/sites-available/pypi-mirror.conf.default 
      dest: /etc/apache2/sites-available/pypi-mirror.conf

- name: Creating a softlink in sites-enabled to the pypi.conf file in sites-available
  file: src=/etc/apache2/sites-available/pypi-mirror.conf dest=/etc/apache2/sites-enabled/pypi-mirror.conf state=link force=yes
  notify: restart apache

- name: Copy the cron job to the pip cron path
  copy: src=usr/local/bin/pip_mirror_cron.sh dest={{ pip_cron_path }}

- name: set up crond job to sync with pypi server
  cron: name="sync bandersnatch  mirror" minute="*/15" job="{{ pip_cron_path }}/pip_mirror_cron.sh"
