---

bandersnatch_virtual_env: /home/bandersnatch
bandersnatch_logger_path: /var/log/bandersnatch/bandersnatch.log
bandersnatch_username: bandersnatch
bandersnatch_home_dir: /home/bandersnatch
apache_pip_mirror_path: /srv/pypi/web/ 
util_server_hostname: mravi2.softlayer.com
util_server_alias: mravi2.softlayer.com
pypi_master_directory: /srv/pypi
pypi_master_url: https://pypi.python.org
